### ISSUE TITLE
Broken links on prospect page

### ISSUE THREAD

**Issue by bmsteele** [Pardot/api-docs#107]
[http://developer.pardot.com/kb/api-version-3/prospects/](http://developer.pardot.com/kb/api-version-3/prospects/)
'Manipulating the Result Set' >> Output
* **'XML Response Formats'**
_Broken link_: http://developer.pardot.com/kb/api-version-3/using-prospects#xml-response-formats 
_Correct link_: http://developer.pardot.com/kb/api-version-3/prospects/#xml-response-formats
* **Using Prospects**
_Broken link_: http://developer.pardot.com/kb/api-version-3/using-prospects#xml-response-formats
_Correct link_: http://developer.pardot.com/kb/api-version-3/prospects/#using-prospects
 
[http://developer.pardot.com/kb/api-version-3/prospects/#querying-prospects](http://developer.pardot.com/kb/api-version-3/prospects/#querying-prospects)
* **_"XML Response Formats"_**
_Broken link_: http://developer.pardot.com/kb/api-version-3/using-prospects#xml-response-formats
_Correct link_:  http://developer.pardot.com/kb/api-version-3/prospects/#xml-response-formats
 
[http://developer.pardot.com/kb/object-field-references/#prospect](http://developer.pardot.com/kb/object-field-references/#prospect)
"Prospect" >> <campaign_id> 
* **'See XML Response Formats'**
_Broken link_: http://developer.pardot.com/kb/object-field-references/prospects#xml-response-formats
_Correct link_: http://developer.pardot.com/kb/api-version-3/prospects/#xml-response-formats

Also, appears like links are broken on the same version /4/ pages

**Comment by joeyrivera** [comment]
Thanks Brian! An internal ticket was created and we'll fix these.

**Comment by joeyrivera** [comment]
Fixed!
