### ISSUE TITLE
How to update the prospect custom field?

### ISSUE THREAD

**Issue by radjivC** [Pardot/api-docs#111]

**Comment by joeyrivera** [comment]
Could you try these and let me know if you have any issues: http://developer.pardot.com/kb/api-version-3/prospects/#updating-fields-with-predefined-values

**Comment by joeyrivera** [comment]
Are these instructions not working? Could you post an example with details of what's happening?

http://developer.pardot.com/kb/api-version-3/prospects/#updating-fields-with-predefined-values

**Comment by radjivC** [comment]
@joeyrivera someone fix the problem for me thanks for the help
