### ISSUE TITLE
Inconsistent email validation

### ISSUE THREAD

**Issue by iamvery** [Pardot/api-docs#120]
I ran into an issue with the Pardot API. I'm not sure if this is the best place to report such problems, so please forgive me if not.

## Problem

Today I noticed what appears to be an inconsistency with email validation in the Pardot API. In particular when creating new prospects via the API an address of the form `lol+wat@haha.com` is considered invalid and the API responds as such, "Invalid prospect email address". However, interestingly the API accepts that exact same email address for prospect updates via the API and successfully updates the prospect.

## Why?

I often take advantage of this little "trick" with Google-hosted email accounts to annotate emails in tests and generally avoid having to use multiple accounts to test things that require different email addresses.

Thank you for your time! Please let me know if I should direct this question to another place.

**Comment by joeyrivera** [comment]
Thanks for reporting this - I just did the test you mentioned here and you are correct. I'll write up a bug ticket so we can address this in the future.

**Comment by iamvery** [comment]
Following up. We had a little more discussion internally about this issue and @seebq found that it's actually an issue with Pardot/ruby-pardot rather than the API itself. So good news! That should be an easier fix. Here's a comment he left me, hope it helps :)

>Good finds. It is a pardot upstream issue, agreed. Your link explains it well, the problem is that this particular API call is submitted as a POST, but with email unencoded as part of the URL /read/by/email/lol+wut@haha.com, which is not a valid URL schema. When email is sent as an API update, the email itself is in the POST and there is no email in the URL (it's a post to /prospects/update/4 or something like that and it can handle it properly in the body. The query string part of the email in the URL needs to be URL encoded and read_by_email uses that.
>
>I know you submitted an issue on the docs, but the real issue is here:
>
>https://github.com/Pardot/ruby-pardot/blob/master/lib/pardot/objects/prospects.rb#L46
>
>That email is in the URL and not encoded. That's where a patch is needed.

**Comment by duncanmcdowell** [comment]
Just in case anyone stumbles across this before it is actually fixed and were not able to fill in the blanks on how to fix. You will need to manually urlencode the email before sending it to the API endpoint.

**Comment by seebq** [comment]
Agreed @duncanmcdowell here's how we did it using ERB::Util standard library:

```
url_encoded_email = ERB::Util.url_encode(email)
client.prospects.read_by_email(url_encoded_email)
```

**Comment by joeyrivera** [comment]
Url-encoding params before sending to the API is the expected way so seems this is a non-issue.

**Comment by iamvery** [comment]
Thanks for following up, @joeyrivera :) Any chance the library could/should perform this encoding for the user?
