### ISSUE TITLE
Developer/Demo account

### ISSUE THREAD

**Issue by emanuelbsilva** [Pardot/api-docs#124]
Hi,

My company wants to integrate with Pardot using the REST API. However i haven't found any information regarding how to create a developer Pardot account. We need that to develop and test the integration. How can we accomplish that?

Thank you,
Best regards,
Emanuel Silva

**Comment by tingham** [comment]
I think you need to contact their sales number:

1-800-667-6389

**Comment by umeshsingh131** [comment]
Hello But this number is not working?

I am a new user of sales force. How i can connect withy pardot technical support team?

**Comment by joeyrivera** [comment]
The support page is a good place to start: https://www.pardot.com/success/support/
You'll find a link to create a support case there.
