### ISSUE TITLE
Possible Documentation Error: Supported Sorting Options for Vistor Activities

### ISSUE THREAD

**Issue by fdacruz1** [Pardot/api-docs#127]
Hi - I think that there is a documentation error in the `Supported Sorting Options` section for the Visitor Activities object for both version 3 and 4 of the API.

The Supported Sorting Options section gives a table with four options to choose from when sorting (see image below)

![image](https://user-images.githubusercontent.com/7267157/33181976-1ef6bfcc-d040-11e7-8fe6-3552c926d99c.png)

The wording for the last row leads to be believe that the option value should be `visitor_id` instead of `prospect_id`.

**Comment by joeyrivera** [comment]
Fixed, thanks!
