### ISSUE TITLE
Update Visitor Activities

### ISSUE THREAD

**Issue by absolutebri** [Pardot/api-docs#132]
Hi all,

Is there a way I am able to update visitor activities manually. The API provides operations like query and read. But the document does not cover about updating visitor activities. Go to the prospect lists, select a prospect, the place where I want to update or customize activities is under the Prospect Activities.

Thank you!
Best Regards,

**Comment by joeyrivera** [comment]
Hi! Currently we don't support a way to insert nor update visitor activities via the API. It's not currently in the roadmap to add this functionality but if it's something you'd use, vote for that feature at the idea exchange: https://success.salesforce.com/ideasearch?filter=Pardot

**Comment by absolutebri** [comment]
Thank you very much for letting me know.
