### ISSUE TITLE
<visitorActivity> should be <visitor_activity>

### ISSUE THREAD

**Issue by cardenw** [Pardot/api-docs#135]
Typo in param
http://developer.pardot.com/kb/api-version-3/visitor-activities/
<visitorActivity>...</visitorActivity>" should be "<visitor_activity>...</visitor_activity>".

query https://pi.pardot.com/api/visitorActivity/version/3/do/query&user_key=XXX&api_key=XXX&sort_order=ascending&type=1

<visitor_activity>
            <type>1</type>....
            <type_name>Email Tracker</type_name>
            <email_id>8677658</email_id>
            <email_template_id>2</email_template_id>
            <campaign>
                <id>54</id>
                <name>Website Tracking</name>
            </campaign>
            <created_at>2016-11-04 13:07:36</created_at>
        </visitor_activity>

**Comment by joeyrivera** [comment]
Fixed, thanks!
