### ISSUE TITLE
<emailClicks> is actually <emailClick>

### ISSUE THREAD

**Issue by cardenw** [Pardot/api-docs#136]
Typo in param
http://developer.pardot.com/kb/api-version-3/batch-email-clicks/
<emailClicks>...</emailClicks>" is actually "<emailClick>...</emailClick>

https://pi.pardot.com/api/emailClick/version/3/do/query?user_key=XXX&api_key=XXX&sort_order=ascending

Returns:
 
<emailClick>
            <id>14674062</id>
            <list_email_id>5962770</list_email_id>
            <email_template_id>2</email_template_id>
            <created_at>2016-10-19 16:55:39</created_at>
        </emailClick>

**Comment by joeyrivera** [comment]
Fixed, thanks!
