### ISSUE TITLE
Version 4 prospect batchUpdate example incorrect

### ISSUE THREAD

**Issue by bmsteele** [pardot/api-docs#142]
http://developer.pardot.com/kb/api-version-4/prospects/#endpoints-for-batch-processing

Example:
/api/prospect/version/4/do/batchUpdate?prospects={"prospects":{"1337":{"first_name":"New first name","last_name":"New last name"},"1234":{"first_name":"New first name","last_name":"New last name"}}}&api_key=&user_key=

Batch actions for v4 require email, id, or fid keys be used:

/api/prospect/version/4/do/batchUpdate?prospects={"prospects":[{"**id**":"1337","first_name":"New first name","last_name":"New last name"}, {"**email**": "art@vandelayindustries.com", "first_name":"New first name","last_name":"New last name"}]}&api_key=&user_key=

**Comment by joeyrivera** [comment]
Indeed, adding ticket on so we can update the docs, thanks!

**Comment by caladdd** [comment]
And It work?
when I try to use the API using JSON I get and error, Error #71: Input needs to be valid JSON or XML
I'm using this
{
       "prospects": 
               [
                    {"id":"number","email":"something@gmail.com"},
                    {"id":"number","email":"something@hotmail.com"}
               ]
}

**Comment by bhavanichandra** [comment]
@caladdd You need to send the prospects as query params, try setting
prospects:{"prospects":[{"email":"bhavanichandra9@live.co.uk","first_name":"Bhavani Chandra","last_name":"Vajapeyayajula"},{"email":"sekharfly1@gmail.com","first_name":"Sekhar","last_name":"Fly"}]}
in query params and try

**Comment by vbastos** [comment]
I also get an error. I'll create an issue.

**Comment by kiserem** [comment]
I too am getting this error.  I'm sending over:

`{ "prospects": [ {"id": 12345, "field_I_want_to_update": "My new value"}]`

I see that the last two comments with this issue are years old, is this just not going to be fixed?

**Comment by adelawalla** [comment]
@kiserem It should work if you set your content type to `application/x-www-form-urlencoded`, and note that the parameter named `prospects` also needs a JSON element named `prospects`. Example:

```
curl --location --request POST 'https://pi.pardot.com/api/prospect/version/4/do/batchUpdate?format=json' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'prospects={
    "prospects": [
        {"id":"1","first_name":"First name","last_name":"Last name"},
        {"id":"2","first_name":"First name","last_name":"Last name"}
    ]
}'
```
