### ISSUE TITLE
Clarify that a Content-Type is necessary. More detailed explanation of error codes. Should GET requests be allowed for authentication?

### ISSUE THREAD

**Issue by lucasxw** [Pardot/api-docs#144]
Hi, I have some feedback here from a Pardot user and am posting on their behalf. 

Pardot API requires that the content-type header is explicitly set in each request to tell the server that the message body is of Content-type: 'application/x-www-form-urlencoded'. This matches the way that the params are chained together in a query string in the example message body in the docs. I noticed that Firefox Web Developer tools that I was using don't explicitly set this header at all - it's omitted from the request altogether, so no content-type was specified to the server. I had to add it manually. I don't know how typical that is of other developer tools, but I guess if other tools do the same this could catch out lots of people. Once I added that Content-type header the authentication succeeded.

The other aspect I wanted to suggest was that I was getting error code 15, but in the page that lists the error codes (http://developer.pardot.com/kb/error-codes-messages), the explanation for code 15 did not help because it suggests that I have one of the email/password/user_key values wrong. I did not, but the url encoding issue might make the server see it that way. In a case like this, maybe a separate error code might help? One that says 'hey, check that your content-type header matches your message body'. Or maybe instead, the description for code 15 in the docs could be extended a little to remind people to check that their content-type header is being included and is correct ? What I'm suggesting seems similar to what you already do for JSON message bodies - I noticed that code 72 deals with JSON encoding - perhaps if that can be detected you could add a code that does something similar for non-JSON message bodies?

Lastly, the authentication section of the page (here http://developer.pardot.com/#authentication) says in the 3 per-requisites that "Authentication requests must use HTTP POST". However I found that GET works as well. Is this intended? Just wanted to alert you to it in case it's meant to be blocked.

**Comment by joeyrivera** [comment]
Thanks for the feedback @lucasxw. GET should not be allowed and we'll have to update this on our end. I just commented on a similar issue at:

https://github.com/Pardot/api-docs/issues/150

A ticket has been created on our system to update the API documentation and make this process more clear.
