### ISSUE TITLE
Prospect custom field 

### ISSUE THREAD

**Issue by mayro** [pardot/api-docs#149]
Hello,
How can i add a custom field to the prospect ? I add a custom field with https://pi.pardot.com/api/customField/version/3/do/create  but i can't find it when i create a prospect

**Comment by ssddanbrown** [comment]
Hi @mayro,

When you create a field, You would have provided a `field_id` property.  You would also see this in the create response data.

You can use this `field_id` value to interact with your field via the API. For example if my field_id was `my_custom_field` I could create a prospect with the following request:

```HTTP
POST https://pi.pardot.com/api/prospect/version/3/do/create/email/hello@example.com?my_custom_field=My-custom-field-value
```

To view the data on the prospect record I could perform the following request:

```HTTP
GET https://pi.pardot.com/api/prospect/version/3/do/read/email/hello@example.com?format=json
```

You should receive a response similar to the below, containing your custom field and new value:

```json
{
    "@attributes": {
        "stat": "ok",
        "version": 1
    },
    "prospect": {
        "id": 123456789,
        "email": "hello@example.com",
        "my_custom_field": "My-custom-field-value",
        ...
    }
}
```

Note that if the prospect does not have a value for your custom field then Pardot will commonly not return it in the response data, The field simply won't exist in the prospect.

**Comment by agosto-chrisbartling** [comment]
@ssddanbrown and @joeyrivera: I'm trying to use @ssddanbrown approach to sending the custom fields and associated values on the HTTP `POST` URL as query parameters as outlined in his June 18th post. I'm using the version 4 of the Pardot API. Does his approach work with the version 4 of the API? I'm curious why custom fields are sent as query parameters and not as part of the `POST` entity-body.

**Comment by simonrl** [comment]
Hi @agosto-chrisbartling , did you find out if this works? Trying to achieve the same. Thanks!

**Comment by vsesumbrame** [comment]
@ssddanbrown I'm trying to update a custom filed type: checkbox. But I don't know what value to assing in query params?
I've tried
POST https://pi.pardot.com/api/prospect/version/3/do/create/email/hello@example.com?my_custom_checkbox_field=true

and

POST https://pi.pardot.com/api/prospect/version/3/do/create/email/hello@example.com?my_custom_checkbox_field=1

For radio button types, value true/false is working.

**Comment by vsesumbrame** [comment]
@joeyrivera Can you help me how to update a custom checkbox field, that has multiple values/checkboxes

**Comment by adelawalla** [comment]
@vsesumbrame See the section on updating [Prospect Fields with Multiple Values](https://developer.salesforce.com/docs/marketing/pardot/guide/prospects-v3.html#updating-fields-with-multiple-values). You must send field values in the body of the request as `x-www-form-urlencoded`, not in the query string. The value you will send depends on how the custom field is configured. In my example, I configured a checkbox field to have values 0 and 1, as such:
<img width="1108" alt="Screenshot 2023-09-13 at 10 09 51" src="https://github.com/pardot/api-docs/assets/4550918/efb19852-f155-438c-b900-ec2cc6c0aff9">

The API call then becomes:
```bash
curl --location --request POST 'https://pi.pardot.com/api/prospect/version/3/do/create?format=json' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Authorization: Bearer <token>' \
--data-urlencode 'email=hello@example.com' \
--data-urlencode 'Checkbox_Field_0=1'
```
