### ISSUE TITLE
[API v3] 'Prospect' query using output=Bulk does NOT return custome field data

### ISSUE THREAD

**Issue by rjiang9** [Pardot/api-docs#151]
We created 2 custom fields 'Job_Function' and 'Position' for prospects. 
When I using '`output=**Bulk**`' to get the prospect data and saved in our DB, these fields data are not included in the returned XML file.
 
But when I query by regular `**output=simple**` (not-bulk) way, they are included. 

Is this a bug or just on purpose?

Thanks,
Jwn

**Comment by rjiang9** [comment]
Here is the powershell code: 
```

$url = "https://pi.pardot.com/api/prospect/version/3/do/query"

  $Params = @{
    "user_key" = $piUSERKEY;
    "api_key" = $api_key;
    "updated_after" = $updated_after;
    "output" = "bulk";
    "sort_by" = "updated_at";
    "sort_order" = "ascending";
  } 

  $R = Invoke-WebRequest -Uri $piUrl -Body $Params -ContentType "application/json" -Method GET           
  $Xml = [xml]$R.Content

```

**Comment by rjiang9** [comment]
Another issue is:

After my powershell script has been running for some time, there will be a time that API returns no results which breaks the loop. Say, I am getting the visitorActivity data, at some point it returns 0 results. I have to keep running the script again and again to get more results. 

Any suggestions are highly appreciated. 

Thanks in advance, 
Jwn

**Comment by joeyrivera** [comment]
This is correct, output=bulk will remove all extra related data by default to make the request more efficient/quicker to execute. However, you can pass in an extra param "fields" equal to a CSV of all standard and custom fields you want to retrieve and they should come back in the query request.

Example:
```
$Params = @{
    "user_key" = $piUSERKEY;
    "api_key" = $api_key;
    "updated_after" = $updated_after;
    "output" = "bulk";
    "sort_by" = "updated_at";
    "sort_order" = "ascending";
    "fields" = "id,first_name,last_name,Job_Function,Position"
  } 
```

**Comment by rjiang9** [comment]
Thank you so much, @joeyrivera . This is very helpful and it helps more people like me if it is stated in the 'bulk' section.

**Comment by joeyrivera** [comment]
@rjiang9 Agreed! I'll add a ticket on our end to update the docs. Thanks!
