### ISSUE TITLE
Start to implement with Pardot Api

### ISSUE THREAD

**Issue by umeshsingh131** [Pardot/api-docs#153]
Hello Team,

I am a new user of salesforce. I want to impelment Pardot API's In my tool. I want to upload all emails through pardot API's  in pardot account, then do campain then display all status in my tool through API.

Please help me here ?

**Comment by joeyrivera** [comment]
Hi, you can see what endpoints we have available at: http://developer.pardot.com/ to plan your implementation. Based on your comment, notice there is no "create email" endpoint available today.
