### ISSUE TITLE
Something wrong with documentation sample code

### ISSUE THREAD

**Issue by dancedric** [Pardot/api-docs#173]
When I just copy-paste the sample code and provide my username, password, and user_key, it results to a 400 bad request. It fails when the curl_exec() line is executed. I wasn't able to dig deeper after that.

Compared to when I tried this url after: http://www.connictech.com/pardot-php-api-sample-add-prospect/

This one actually worked just after copy-pasting. Echo is needed to display your api_key.

**Comment by dancedric** [comment]
In addition to the 400 bad request, if I just copy the generated url and paste it in the browser, it works and returns a proper XML  response with "ok". I added useragent in the curl_setopt() after but still 400 bad request.

**Comment by jordif** [comment]
Hi @dancedric ,

I encountered the same issue. I had to change the code so that the parameters were sent in the body of the request (using the CURLOPT_POSTFIELDS option).

Cheers

**Comment by adelawalla** [comment]
Documented here: http://developer.pardot.com/#using-the-api
