### ISSUE TITLE
API - Get all email template ids

### ISSUE THREAD

**Issue by dattajoshi** [pardot/api-docs#204]
Hi,

Is it possible to get all email template ids with their names from the API.

In the API i see that there is a endpoint /api/emailTemplate/version/4/do/read/id/<email template id> (http://developer.pardot.com/kb/api-version-3/email-templates/) which expects email template id. But i want the get all template ids.

Help is appreciated

**Comment by jpearson-sfdc** [comment]
The API only offers the capability to retrieve an Email Template by ID with the [read endpoint](http://developer.pardot.com/kb/api-version-3/email-templates/) and to get a [list of emails enabled for one to one](http://developer.pardot.com/kb/api-version-3/email-templates/#list-one-to-one-email-templates). There is not an endpoint to query all email templates.
