### ISSUE TITLE
Max characters

### ISSUE THREAD

**Issue by northernbeacheswebsites** [pardot/api-docs#207]
Hi, what is the maximum characters that are acceptable via the API. I have a user with a custom field saying that if they have over 3000 characters it won't work. It would be good if this limit was specified in the documentation and/or a remedy was outlined. Thanks,

**Comment by adelawalla** [comment]
@northernbeacheswebsites Could you give us a sample of the code being used?

**Comment by northernbeacheswebsites** [comment]
Hi @adelawalla the code used is not super relevant because the code has a lot of settings and what not, but it's in PHP and looks like:

`$url = $apiBase.'prospect/version/'.$apiVersion.'/do/upsert/email/'.urlencode($email).'?'.$build_query;
                    $response = wp_remote_post($url, array(
                        'headers' => array(
                            'Authorization' => 'Pardot api_key='.$apiKey.', user_key='.$userKey,
                        ),
                    ));`

The client using the code is saying that when they create the prospect with a custom field value greater than 3000 characters, it won't create the prospect via the API. Note the custom field they have setup is a textarea field with a character limit of 65,535 characters (see: https://www.pardot.com/blog/custom-fields/). What I suspect is there's a limit on the amount of characters allowed via the API for custom fields which is much smaller then the actual field allowance in Pardot, or there's perhaps a limit on the amount of characters in the query string. It would be good if I had some clarification on these limits. Thanks,

**Comment by adelawalla** [comment]
Ah yes, we think that there is a limit being imposed on the query string. If they could, try moving the value to the body of the message instead. The limit there should be much bigger, and allow for the full usage of the field.

**Comment by northernbeacheswebsites** [comment]
Thank you, I will test this out, but for now I will close this. Thanks once again,
