### ISSUE TITLE
API - %%unsubscribe%% vs {{unsubscribe}}

### ISSUE THREAD

**Issue by stojankoncar** [pardot/api-docs#211]
Using the /api/email/version/4/do/send we are able to send/schedule emails.
One of the required fields is

text_content | x* | string | The text body of the email. This must contain either %%unsubscribe%% or %%email_preference_center%%.

The same rules are applied for html_content field.

Nothing wrong with that.

When we try to edit the HTML (submited using the API) with the editor in Pardot, an error appears:

<img width="1676" alt="Screenshot 2019-12-26 at 11 15 17" src="https://user-images.githubusercontent.com/39338615/71471870-24f67080-27d1-11ea-8fbb-4950a87d8022.png">

Looks like the %%unsubscribe%% is outdated - but without it - it's not possible to submit the API request.

Is there are maybe v5 of your API which supports new handlebar syntax or some workaround for us?

Best,
Stojan

**Comment by jpearson-sfdc** [comment]
I've notified the Email team (W-7059680). If you need support soon, please contact [Pardot Support](https://help.salesforce.com/articleView?id=000331766&type=1&mode=1).
