### ISSUE TITLE
Unable to query the Lists. 

### ISSUE THREAD

**Issue by vnktsf** [pardot/api-docs#214]
Hello, I just started using Pardot API... I was able to pass the username, password and key and got the api key. However when I try to GET the list by passing the userkey and api key (using http://developer.pardot.com/kb/api-version-3/lists/ this documentation ) I always get a     <err code="1">Invalid API key or user key</err>. 

Im using psotman to test the api. Can some one please successfully use the Pardot api

**Comment by jpearson-sfdc** [comment]
Authentication is described in the [Authentication section on the Overview page](http://developer.pardot.com/#authentication) in the documentation. 

We do not provide support for the product on this repo as it's only related to the documentation. If you need assistance or support, please contact Pardot Support via one of the means listed on our [support page](https://www.pardot.com/success/support/).
