### ISSUE TITLE
Authentication request returns access denied error 49 

### ISSUE THREAD

**Issue by muralib36** [pardot/api-docs#215]
When i am sending authentication request to the Pardot API for api key it returns error code 49. In documentation authorization header is required it requires both user key and api key.

```
$loginResponse = callPardotApi('https://pi.pardot.com/api/login/version/4',
    array(
        'email' => 'your.email@example.com',
        'password' => 'password1234',
        'user_key' => $userKey,
        'format' => 'json'
    ),
    'POST'
);
```
`Array ( [@attributes] => Array ( [stat] => fail [version] => 1 [err_code] => 49 ) [err] => Access Denied )`

**Comment by Art-em1s** [comment]
From their support:

>  First of all, please note you need to use the version 4 for all your calls as you have AMPSEA enabled (https://help.salesforce.com/articleView?id=pardot_admin_ampsea_parent.htm&type=5). 
> 
> Also, there was a change made on the 14th of February that means you will no longer be able to authenticate with the Pardot API using an HTTP authorisation header, which essentially translates to not being able to authenticate with the Pardot API using your credentials in the URL/header. 
> 
> For example, you will no longer be able to authenticate with Pardot and generate an API key using the following method: 
> 
> https://pi.pardot.com/api/login/version/4?email=example@salesforce.com&password=XXXXXXXXX&user_key=XXXXXXX 
> 
> You would need to have your credentials as parameters in the body of the API request, as mentioned in the Pardot API documentation below: 
> 
> http://developer.pardot.com/#authentication

Something to note, the method stated doesn't work and their API documentation that they link to says something completely different.

**Comment by j-douglas-tf** [comment]
You'll need to switch to a different way of doing your CURL - the documentation tells you to switch, but doesn't tell you WHAT to do instead - this is what i've written, and it's working for me!

$curl    = curl_init();

		curl_setopt_array( $curl, array(
			CURLOPT_URL            => $this->url,
			CURLOPT_RETURNTRANSFER => true,
			CURLOPT_ENCODING       => "",
			CURLOPT_MAXREDIRS      => 10,
			CURLOPT_TIMEOUT        => 30,
			CURLOPT_HTTP_VERSION   => CURL_HTTP_VERSION_1_1,
			CURLOPT_CUSTOMREQUEST  => "POST",
			CURLOPT_POSTFIELDS     => 'email='.$this->email.'&password='.$this->password.'&user_key='.$this->user_key,
			CURLOPT_HTTPHEADER     => array(
				"cache-control: no-cache",
				"content-type: application/x-www-form-urlencoded",
			)
		));

		$response = curl_exec($curl);
		$err = curl_error($curl);

		curl_close($curl);

		$xml  = new SimpleXMLElement( $response );
		$obj  = $xml->api_key;
		$key  = (string) $obj{0};
		return $key;

**Comment by Art-em1s** [comment]
Interestingly, the above works in postman, but not in php, returning "Login Failed".

**Comment by muralib36** [comment]
> You'll need to switch to a different way of doing your CURL - the documentation tells you to switch, but doesn't tell you WHAT to do instead - this is what i've written, and it's working for me!
> 
> $curl = curl_init();
> 
> ```
> 	curl_setopt_array( $curl, array(
> 		CURLOPT_URL            => $this->url,
> 		CURLOPT_RETURNTRANSFER => true,
> 		CURLOPT_ENCODING       => "",
> 		CURLOPT_MAXREDIRS      => 10,
> 		CURLOPT_TIMEOUT        => 30,
> 		CURLOPT_HTTP_VERSION   => CURL_HTTP_VERSION_1_1,
> 		CURLOPT_CUSTOMREQUEST  => "POST",
> 		CURLOPT_POSTFIELDS     => 'email='.$this->email.'&password='.$this->password.'&user_key='.$this->user_key,
> 		CURLOPT_HTTPHEADER     => array(
> 			"cache-control: no-cache",
> 			"content-type: application/x-www-form-urlencoded",
> 		)
> 	));
> 
> 	$response = curl_exec($curl);
> 	$err = curl_error($curl);
> 
> 	curl_close($curl);
> 
> 	$xml  = new SimpleXMLElement( $response );
> 	$obj  = $xml->api_key;
> 	$key  = (string) $obj{0};
> 	return $key;
> ```

Now it is working fine Thanks.

**Comment by jpearson-sfdc** [comment]
Authentication is documented in the [developer documentation](http://developer.pardot.com/#authentication). This source repository is for the documentation and is not a channel for support. If you need assistance or help with Pardot, please contact [Pardot Support](https://help.salesforce.com/articleView?id=000331766&type=1&mode=1).

**Comment by dattajoshi** [comment]
> From their support:
> 
> > First of all, please note you need to use the version 4 for all your calls as you have AMPSEA enabled (https://help.salesforce.com/articleView?id=pardot_admin_ampsea_parent.htm&type=5).
> > Also, there was a change made on the 14th of February that means you will no longer be able to authenticate with the Pardot API using an HTTP authorisation header, which essentially translates to not being able to authenticate with the Pardot API using your credentials in the URL/header.
> > For example, you will no longer be able to authenticate with Pardot and generate an API key using the following method:
> > https://pi.pardot.com/api/login/version/4?email=example@salesforce.com&password=XXXXXXXXX&user_key=XXXXXXX
> > You would need to have your credentials as parameters in the body of the API request, as mentioned in the Pardot API documentation below:
> > http://developer.pardot.com/#authentication
> 
> Something to note, the method stated doesn't work and their API documentation that they link to says something completely different.

@Art-em1s Did you have any luck on this? I'm trying the same way, but in Python. It's working only if the Content-type is  "application/x-www-form-urlencoded", but if it's JSON it's failing.

**Comment by jpearson-sfdc** [comment]
@dattajoshi 

If you are using the "requests" module:

```py
import requests, json

userKey = '<user_key>'
password = '<password>'
email = '<email>'

r = requests.post('https://pi.pardot.com/api/login', params = {'format': 'json'}, data = {'user_key': userKey, 'email': email, 'password': password})
j = json.loads(r.text)
print(j['api_key'])
```

If you are using the standard Python 3 libraries:
```py
import http.client, urllib.parse, json

userKey = '<user_key>'
password = '<password>'
email = '<email>'

params = urllib.parse.urlencode({'user_key': userKey, 'email': email, 'password': password});
headers = {"Content-type": "application/x-www-form-urlencoded"}

conn = http.client.HTTPSConnection('pi.pardot.com')
conn.request('POST', '/api/login?format=json', params, headers)
response = conn.getresponse()
data = response.read()
conn.close()

j = json.loads(data)
print(j['api_key'])
```
