### ISSUE TITLE
Updated PHP sample from with new API Auth requirements http://developer.pardot.com/

### ISSUE THREAD

**Issue by crakage** [pardot/api-docs#217]
Hi team, 

The PHP sample is still using query string and cause error 49, sample available here:
https://github.com/pardot/api-docs/blob/master/docs/index.md

I am not confident enough with my PHP to do a pull request, but I tried to update the code it works for me at least but I let you test and update if needed: 
https://gist.github.com/crakage/b89dbcff44e1701a29f9bf0eed63c5c2

I left \* comments */ of what I changed and just commented out (//) the existing lines

Regards
David

**Comment by gabeshaughnessy** [comment]
Thanks for posting this David, this was giving me so many headaches, it also fixed the issue for me.

**Comment by crakage** [comment]
They just edited the documentation with a new version working fine and change to use classes
