### ISSUE TITLE
OAuth in react-native

### ISSUE THREAD

**Issue by Shing-Ho** [pardot/api-docs#224]
What should I have to do for oauth in react-native? In salesforce, I created app for get client_id and client_secret, what should I have to do in here? Can I get refresh token?

**Comment by jpearson-sfdc** [comment]
Authentication is documented in the [developer documentation](http://developer.pardot.com/#authentication). This source repository is for the documentation and is not a channel for support. If you need assistance or help with Pardot, please contact [Pardot Support](https://help.salesforce.com/articleView?id=000331766&type=1&mode=1).

**Comment by Shing-Ho** [comment]
Thanks @jpearson-sfdc 
But I couldn't contact pardot support with http://www2.pardot.com/help/case/
It is showing error, and it seems I should login to https://help.salesforce.com/home
But couldn't login with my sf credentials. How can I handle this?
Thanks in advance
