### ISSUE TITLE
[CustomFields] How do you get dropdown values?

### ISSUE THREAD

**Issue by kaddyadriano** [pardot/api-docs#226]
Is there a way to get CustomField dropdown values directly from Pardot api? Return predefined values if the custom field is not synced with Salesforce.

**Comment by jpearson-sfdc** [comment]
This source repository is for documentation and is not a channel for support. Custom fields and their functionality are documented under the [Custom Field section](https://developer.pardot.com/kb/api-version-3/custom-fields/). If you need assistance or help with Pardot, please contact [Pardot Support](https://help.salesforce.com/articleView?id=000331766&type=1&mode=1).
