### ISSUE TITLE
Access Denied via Salesforce OAuth

### ISSUE THREAD

**Issue by K4v3ZpdA** [pardot/api-docs#231]
Salesforce Summer '20 released so I tried to switch from Pardot API login endpoint to Salesforce OAuth for authentication.
I am able to get the access token but it gives the following error when I make a post request with it and the Pardot Business Unit ID.
`<err code="49">Access Denied</err>`

I am passing headers as that mentioned in the documentation.
> Authorization: Bearer <access_token>
> Pardot-Business-Unit-Id: <business_unit_id>

Any idea?

**Comment by noshirpatel-salesforce** [comment]
As of the time of this post, use of Salesforce OAuth with Pardot had not yet been enabled for all customers.  It has now been enabled.

**Comment by K4v3ZpdA** [comment]
> As of the time of this post, use of Salesforce OAuth with Pardot had not yet been enabled for all customers. It has now been enabled.

Thank you, it works now.
