### ISSUE TITLE
Typos on Object Field References Page

### ISSUE THREAD

**Issue by humeansacrifice** [Pardot/api-docs#33]
In Opportunity table's description column, 'Opportunity' is spelled incorrectly on several entries:

* name
* type
* stage

Page URL: http://developer.pardot.com/kb/api-version-3/object-field-references/
Screenshot: http://www.screencast.com/t/GZ6MJOsX4Q

**Comment by et** [comment]
@humeansacrifice - can this be closed?

**Comment by humeansacrifice** [comment]
Looks like @et thanks!
