### ISSUE TITLE
Add info about batch things

### ISSUE THREAD

**Issue by bmsteele** [Pardot/api-docs#41]
Add documentation about
/api/prospect/version/3/do/batchCreate
/api/prospect/version/3/do/batchUpdate
/api/prospect/version/3/do/batchUpsert

**Comment by StephieG** [comment]
Looks like we should add batchQuery to the Supported Operations section under Querying Prospects (http://developer.pardot.com/kb/api-version-3/prospects/#querying-prospects), and add batchCreate, batchUpdate, and batchUpsert to the Supported Operations section under Using Prospects (http://developer.pardot.com/kb/api-version-3/prospects/#using-prospects).
