### ISSUE TITLE
Broken Links to fix 

### ISSUE THREAD

**Issue by humeansacrifice** [pardot/api-docs#62]
- http://developer.pardot.com/20object-field-references - ref'd from: http://developer.pardot.com/kb/api-version-3/prospects/
- http://developer.pardot.com/authentication - ref'd from: http://developer.pardot.com/kb/api-version-3/error-codes-messages/
- http://developer.pardot.com/kb/api-version-3/error-codes-and-messages - ref'd from: http://developer.pardot.com/kb/api-version-3/prospects/
- http://developer.pardot.com/kb/api-version-3/object-field%20references (note: bad escaped URL) - ref'd from: http://developer.pardot.com/kb/api-version-3/users/ AND http://developer.pardot.com/kb/api-version-3/opportunities/
- http://developer.pardot.com/kb/api-version-3/visitors-activities - ref'd from: http://developer.pardot.com/kb/api-version-3/visitor-activities/ (singular: visitor-, not visitors-)
- http://developer.pardot.com/object-field-references - ref'd from: http://developer.pardot.com/kb/api-version-3/visitor-activities/
- http://developer.pardot.com/using-prospects - ref'd from: http://developer.pardot.com/kb/api-version-3/visitors/ (twice on page) AND http://developer.pardot.com/kb/api-version-3/prospects/ (5x on page)

**Comment by joeyrivera** [comment]
Fixed all the broken links under v3/v4 for prospects. Need to do the others.

**Comment by creuzerm** [comment]
The link to creating a ticket on the first bullet point of http://developer.pardot.com/ is now broken with the switch to Salesforce ticket handling.

**Comment by joeyrivera** [comment]
Thanks @creuzerm the link has been fixed!

**Comment by jpearson-sfdc** [comment]
These links specified above do not appear to be broken today.
