### ISSUE TITLE
API v4, visitors article: assigning visitors by prospect_email

### ISSUE THREAD

**Issue by bmsteele** [Pardot/api-docs#86]
In v4, prospect_email cannot be used to assign a visitor

http://developer.pardot.com/kb/api-version-4/visitors/#using-visitors
Remove reference to prospect_email and reword the grammarz.

**Comment by joshua-stewart** [comment]
The documentation is still incorrect as indicated above and needs to be updated.

**Comment by joeyrivera** [comment]
Fixed!
