### ISSUE TITLE
Pardot API usage: abnormal scoring

### ISSUE THREAD

**Issue by aistis-** [Pardot/api-docs#90]
Hi guys,

my apologies for reporting an issue in the doc repo, but I am hoping to reach the developers who is working on Pardot API or at least has a solid technical knowledge around it.

Long story short:
* **We are using Pardot from 2016 ~January via Pardot forms**:
  * We added JavaScript by [example](http://help.pardot.com/customer/portal/articles/2133733-implementing-tracking-code).
  * Prospect were created by iframe on success registration page:
    * A visitor browses on our website
    * Decides to register, fills the registration form
    * On success registration page we use `<iframe>` to send Prospect data via `HTTPS GET` to Pardot where Prospect is created and associated to a visitor (by cookie).
* **On 2016 ~ June we replace `<iframe>` solution by Pardot API implementation**.
  * `<iframe>` is not a reliable approach to create Prospects as we noticed we loosing some of them (visitor does not wait a registration success page or whatever is the reason)
  * We implement Pardot API by two requests to Pardot: [creating a Prospect](http://developer.pardot.com/kb/api-version-3/prospects/#creating-prospects) and [assigning visitor](http://developer.pardot.com/kb/api-version-3/visitors/#assigning-and-reassigning-visitors) to the prospect.
    * `visitor_id` is extracted from visitor's cookie
    * Response from Pardot are valid and looks totally legit
    * The behavior when testing looks as expected

**Problem:**

Some time after starting using the API we noticed, that Prospects became having abnormal scoring - very high amount of points. When auditing the prospect, we could see, that visitors are [reassigned between same Propsects multiple times in same second](https://sc-cdn.scaleengine.net/i/4804fd29a34fbd2e60002bcd37e44213.png).

Could it happen we are using an incorrect flow of API implementation? Any other ideas of the problem? The prospects who are merged, seems as real persons, who found the website in different ways: email, ads, direct URL - our sales guys have been on the phone with each of them.

API implementation:
![Schema](https://sc-cdn.scaleengine.net/i/832eedd5915c974484f0e32bb9cfcb81.png)

*If it happen, that you are interested in the case, please do not hesitate and take a look into Pardot case (number 305684) for more details (logs, code snippets etc.).*

**Comment by joeyrivera** [comment]
Hi aistis, I'm going to see if I can find you some help and see who's helping with that case. There shouldn't be any logic in the API that would cause visitors to get reassigned multiple times between the prospects but I can do a quick test. So first you have a visitor id. Then you make an API call to create a prospect. Finally you make another API call to assign the visitor id to the newly created prospect?

**Comment by aistis-** [comment]
Hi @joeyrivera!

Yes! You you got the flow totally right! But we are facing unexpected merging too :(
See the last messages in the case. One of your guys succeeded to replicate the merging. I attached the logs of the exact Prospect creation and Assigning to the case.

**Comment by joeyrivera** [comment]
Hi Aistis,

I did a few tests and got the expected results on my end testing with the API. I even ran the assign endpoint a few times to see if it would cause some oddities in the data but it didn't seem to do anything. I'm assuming the issue would have to be with the way the scoring is happening or any dynamic rules taking place that could be affected if the assigning happens multiple times.

You see the reassigning taking place in the audits - if you look at your logs, is your system making the same api call multiple times? My next recommendation would be to make sure your system isn't making the same API calls multiple times by accident. I also see you and Joe are talking in more details about this in the case. I'll reach out to him and see how we can join efforts.
