### ISSUE TITLE
Assigning tags to new prospects

### ISSUE THREAD

**Issue by cah-alexsukhodolsky** [Pardot/api-docs#92]
I'm working on adding new/updating existing prospects using the `https://pi.pardot.com/api/prospect/version/3/do/upsert/email?email={email}` api endpoint. One of my requirements is to add a tag into the `tags` field for the new prospect (found under Pardot prospects' "Additional Fields" section).

How do I update the URL above to populate the tag field with a single tag?

Thanks!

**Comment by joeyrivera** [comment]
I'll try and see what I can find out and report back.

**Comment by joeyrivera** [comment]
It doesn't seem like we support creating new tag objects: http://developer.pardot.com/kb/api-version-3/tag-objects/ and only allow query/read via the API and that's where that relationship is set. The prospect end point doesn't seem to allow passing in tags as parameters to create/update.

I'd recommend making a request over in the idea exchange: https://success.salesforce.com/ideasearch?filter=Pardot+%3E+Connectors+%26+API 

That list helps us make decisions on what features our customers are asking for.

**Comment by dougblackjr** [comment]
It's been over a year. Is this still the case that I can't add a tag to a prospect via the API?

**Comment by cah-alexsukhodolsky** [comment]
I'm actually no longer working on the project.
